# Generated by Django 2.0.2 on 2018-02-26 13:59

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('courseName', models.CharField(max_length=30, verbose_name='课程名称')),
                ('courseCredit', models.CharField(max_length=3, verbose_name='课程学分')),
                ('courseMajor', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='management.Major', verbose_name='所属专业')),
                ('coutseInstitute', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='management.Institute', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
