# Generated by Django 2.0.2 on 2018-03-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '审核中'), ('1', '批准'), ('2', '不同意')], default='0', max_length=2)),
                ('applyCourseAddTime', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherUser', verbose_name='申请教师')),
                ('teacherApplyCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '学生选课表',
                'verbose_name_plural': '学生选课表',
                'ordering': ['applyCourseAddTime'],
            },
        ),
    ]
