# Generated by Django 2.0.2 on 2018-03-04 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_teacherapplycourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherapplycourse',
            options={'ordering': ['applyCourseAddTime'], 'verbose_name': '教师申请课程表', 'verbose_name_plural': '教师申请课程表'},
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='selectCourseAllNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='课程总人数'),
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='selectCourseClassTime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.ClassTime', verbose_name='上课时间'),
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='selectCourseClassroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Classroom', verbose_name='上课教室'),
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='selectCourseNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='已选人数'),
        ),
        migrations.AlterField(
            model_name='teacherapplycourse',
            name='status',
            field=models.CharField(choices=[('审核中', '审核中'), ('批准', '批准'), ('不同意', '不同意')], default='0', max_length=2, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='teacherapplycourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherUser', verbose_name='教师工号'),
        ),
    ]
