# Generated by Django 2.0.2 on 2018-02-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_studentselectcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentselectcourse',
            name='studentSelectCourse_score',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='成绩'),
        ),
    ]
