# Generated by Django 2.0.2 on 2018-02-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180227_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coutseInstitute',
            new_name='courseInstitute',
        ),
        migrations.AlterField(
            model_name='studentselectcourse',
            name='studentSelectCourse_stduent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentUser', verbose_name='学生学号'),
        ),
    ]
