# Generated by Django 2.0.2 on 2018-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, verbose_name='用户姓名'),
        ),
    ]
