# Generated by Django 2.0.2 on 2018-02-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('0', '教师'), ('1', '学生')], default='0', max_length=1, verbose_name='用户身份'),
        ),
    ]
