# Generated by Django 2.0.2 on 2018-02-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_identity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identity',
            new_name='userIdentity',
        ),
    ]
