# Generated by Django 2.0.2 on 2018-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180226_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userIdentity',
            field=models.CharField(choices=[('教师', '教师'), ('学生', '学生')], default='学生', max_length=2, verbose_name='用户身份'),
        ),
    ]
