# Generated by Django 2.0.2 on 2018-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180225_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='--', max_length=20, verbose_name='用户姓名'),
        ),
    ]
