# Generated by Django 2.0.2 on 2018-02-26 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '__first__'),
        ('users', '0002_auto_20180226_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('teacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.User', verbose_name='教师工号')),
                ('teacherSex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1, verbose_name='性别')),
                ('teacherInstitute', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='management.Institute', verbose_name='学院')),
            ],
        ),
    ]
