# Generated by Django 2.0.2 on 2018-02-26 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20180226_1631'),
        ('management', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.User', verbose_name='学生学号')),
                ('studentSex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1, verbose_name='性别')),
                ('studentClass', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='management.Class', verbose_name='班级')),
                ('studentInstitute', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='management.Institute', verbose_name='学院')),
                ('studentMajor', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='management.Major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
    ]
